name: update source image

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  debian-cloud-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: update cloud image source
        run: |
          ./.github/workflows/scripts/check-debian-cloud-image-update.sh
          make debian-base-validate

      - name: create pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump Debian cloud image"
          title: "chore: bump Debian cloud image"
          body: |
            Automated update of Debian cloud image.
          branch: chore/debian-cloud-image-bump
          delete-branch: true

  debian-base-update:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: update base image source
        run: |
          ./.github/workflows/scripts/check-debian-base-image-update.sh
          make debian-container-validate
          make debian-kubernetes-validate

      - name: create pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump Debian base image"
          title: "chore: bump Debian base image"
          body: |
            Automated update of Debian base image.
          branch: chore/debian-base-image-bump
          delete-branch: true
