name: run validations

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: [self-hosted]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup packer
        uses: hashicorp/setup-packer@main

      - name: validate
        run: |
          make debian-base-validate
          make debian-container-validate
          make debian-kubernetes-validate
          shellcheck ./.github/workflows/scripts/*
